require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PlannedHolidaysController do

  # This should return the minimal set of attributes required to create a valid
  # PlannedHoliday. As you add validations to PlannedHoliday, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { 
      :user_id=> FactoryGirl.build(:user).id,
      :approver_id=> FactoryGirl.build(:user).id,
      :holiday_type_id=>2,
      :term_start=> "2013.01.01",
      :term_end=>"2013.01.02"
    }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PlannedHolidaysController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all planned_holidays as @planned_holidays" do
      planned_holiday = PlannedHoliday.create! valid_attributes
      get :index, {}, valid_session
      assigns(:planned_holidays).should eq([planned_holiday])
    end
  end

  describe "GET show" do
    it "assigns the requested planned_holiday as @planned_holiday" do
      planned_holiday = PlannedHoliday.create! valid_attributes
      get :show, {:id => planned_holiday.to_param}, valid_session
      assigns(:planned_holiday).should eq(planned_holiday)
    end
  end

  describe "GET new" do
    it "assigns a new planned_holiday as @planned_holiday" do
      get :new, {}, valid_session
      assigns(:planned_holiday).should be_a_new(PlannedHoliday)
    end
  end

  describe "GET edit" do
    it "assigns the requested planned_holiday as @planned_holiday" do
      planned_holiday = PlannedHoliday.create! valid_attributes
      get :edit, {:id => planned_holiday.to_param}, valid_session
      assigns(:planned_holiday).should eq(planned_holiday)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PlannedHoliday" do
        expect {
          post :create, {:planned_holiday => valid_attributes}, valid_session
        }.to change(PlannedHoliday, :count).by(1)
      end

      it "assigns a newly created planned_holiday as @planned_holiday" do
        post :create, {:planned_holiday => valid_attributes}, valid_session
        assigns(:planned_holiday).should be_a(PlannedHoliday)
        assigns(:planned_holiday).should be_persisted
      end

      it "redirects to the created planned_holiday" do
        post :create, {:planned_holiday => valid_attributes}, valid_session
        response.should redirect_to(PlannedHoliday.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved planned_holiday as @planned_holiday" do
        # Trigger the behavior that occurs when invalid params are submitted
        PlannedHoliday.any_instance.stub(:save).and_return(false)
        post :create, {:planned_holiday => { "user" => "invalid value" }}, valid_session
        assigns(:planned_holiday).should be_a_new(PlannedHoliday)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PlannedHoliday.any_instance.stub(:save).and_return(false)
        post :create, {:planned_holiday => { "user" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested planned_holiday" do
        planned_holiday = PlannedHoliday.create! valid_attributes
        # Assuming there are no other planned_holidays in the database, this
        # specifies that the PlannedHoliday created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PlannedHoliday.any_instance.should_receive(:update_attributes).with({ "user" => "" })
        put :update, {:id => planned_holiday.to_param, :planned_holiday => { "user" => "" }}, valid_session
      end

      it "assigns the requested planned_holiday as @planned_holiday" do
        planned_holiday = PlannedHoliday.create! valid_attributes
        put :update, {:id => planned_holiday.to_param, :planned_holiday => valid_attributes}, valid_session
        assigns(:planned_holiday).should eq(planned_holiday)
      end

      it "redirects to the planned_holiday" do
        planned_holiday = PlannedHoliday.create! valid_attributes
        put :update, {:id => planned_holiday.to_param, :planned_holiday => valid_attributes}, valid_session
        response.should redirect_to(planned_holiday)
      end
    end

    describe "with invalid params" do
      it "assigns the planned_holiday as @planned_holiday" do
        planned_holiday = PlannedHoliday.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PlannedHoliday.any_instance.stub(:save).and_return(false)
        put :update, {:id => planned_holiday.to_param, :planned_holiday => { "user" => "invalid value" }}, valid_session
        assigns(:planned_holiday).should eq(planned_holiday)
      end

      it "re-renders the 'edit' template" do
        planned_holiday = PlannedHoliday.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PlannedHoliday.any_instance.stub(:save).and_return(false)
        put :update, {:id => planned_holiday.to_param, :planned_holiday => { "user" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested planned_holiday" do
      planned_holiday = PlannedHoliday.create! valid_attributes
      expect {
        delete :destroy, {:id => planned_holiday.to_param}, valid_session
      }.to change(PlannedHoliday, :count).by(-1)
    end

    it "redirects to the planned_holidays list" do
      planned_holiday = PlannedHoliday.create! valid_attributes
      delete :destroy, {:id => planned_holiday.to_param}, valid_session
      response.should redirect_to(planned_holidays_url)
    end
  end

end
