require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PlannedWorkTimesController do

  # This should return the minimal set of attributes required to create a valid
  # PlannedWorkTime. As you add validations to PlannedWorkTime, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "user" => "" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PlannedWorkTimesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all planned_work_times as @planned_work_times" do
      planned_work_time = PlannedWorkTime.create! valid_attributes
      get :index, {}, valid_session
      assigns(:planned_work_times).should eq([planned_work_time])
    end
  end

  describe "GET show" do
    it "assigns the requested planned_work_time as @planned_work_time" do
      planned_work_time = PlannedWorkTime.create! valid_attributes
      get :show, {:id => planned_work_time.to_param}, valid_session
      assigns(:planned_work_time).should eq(planned_work_time)
    end
  end

  describe "GET new" do
    it "assigns a new planned_work_time as @planned_work_time" do
      get :new, {}, valid_session
      assigns(:planned_work_time).should be_a_new(PlannedWorkTime)
    end
  end

  describe "GET edit" do
    it "assigns the requested planned_work_time as @planned_work_time" do
      planned_work_time = PlannedWorkTime.create! valid_attributes
      get :edit, {:id => planned_work_time.to_param}, valid_session
      assigns(:planned_work_time).should eq(planned_work_time)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PlannedWorkTime" do
        expect {
          post :create, {:planned_work_time => valid_attributes}, valid_session
        }.to change(PlannedWorkTime, :count).by(1)
      end

      it "assigns a newly created planned_work_time as @planned_work_time" do
        post :create, {:planned_work_time => valid_attributes}, valid_session
        assigns(:planned_work_time).should be_a(PlannedWorkTime)
        assigns(:planned_work_time).should be_persisted
      end

      it "redirects to the created planned_work_time" do
        post :create, {:planned_work_time => valid_attributes}, valid_session
        response.should redirect_to(PlannedWorkTime.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved planned_work_time as @planned_work_time" do
        # Trigger the behavior that occurs when invalid params are submitted
        PlannedWorkTime.any_instance.stub(:save).and_return(false)
        post :create, {:planned_work_time => { "user" => "invalid value" }}, valid_session
        assigns(:planned_work_time).should be_a_new(PlannedWorkTime)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PlannedWorkTime.any_instance.stub(:save).and_return(false)
        post :create, {:planned_work_time => { "user" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested planned_work_time" do
        planned_work_time = PlannedWorkTime.create! valid_attributes
        # Assuming there are no other planned_work_times in the database, this
        # specifies that the PlannedWorkTime created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PlannedWorkTime.any_instance.should_receive(:update_attributes).with({ "user" => "" })
        put :update, {:id => planned_work_time.to_param, :planned_work_time => { "user" => "" }}, valid_session
      end

      it "assigns the requested planned_work_time as @planned_work_time" do
        planned_work_time = PlannedWorkTime.create! valid_attributes
        put :update, {:id => planned_work_time.to_param, :planned_work_time => valid_attributes}, valid_session
        assigns(:planned_work_time).should eq(planned_work_time)
      end

      it "redirects to the planned_work_time" do
        planned_work_time = PlannedWorkTime.create! valid_attributes
        put :update, {:id => planned_work_time.to_param, :planned_work_time => valid_attributes}, valid_session
        response.should redirect_to(planned_work_time)
      end
    end

    describe "with invalid params" do
      it "assigns the planned_work_time as @planned_work_time" do
        planned_work_time = PlannedWorkTime.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PlannedWorkTime.any_instance.stub(:save).and_return(false)
        put :update, {:id => planned_work_time.to_param, :planned_work_time => { "user" => "invalid value" }}, valid_session
        assigns(:planned_work_time).should eq(planned_work_time)
      end

      it "re-renders the 'edit' template" do
        planned_work_time = PlannedWorkTime.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PlannedWorkTime.any_instance.stub(:save).and_return(false)
        put :update, {:id => planned_work_time.to_param, :planned_work_time => { "user" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested planned_work_time" do
      planned_work_time = PlannedWorkTime.create! valid_attributes
      expect {
        delete :destroy, {:id => planned_work_time.to_param}, valid_session
      }.to change(PlannedWorkTime, :count).by(-1)
    end

    it "redirects to the planned_work_times list" do
      planned_work_time = PlannedWorkTime.create! valid_attributes
      delete :destroy, {:id => planned_work_time.to_param}, valid_session
      response.should redirect_to(planned_work_times_url)
    end
  end

end
